# The pipeline builds the docker image, tags it as 'latest' and pushes it to the Docker Hub

variables:
  - group: AzureKeyVault
  - name: repository
    value: griffinplus/strongswan-client-route-manager
  - name: image_tag
    value: latest
  - name: registry_user
    value: $(dockerhub-user)
  - name: registry_password
    value: $(dockerhub-password)
  - name: basedir
    value: $(Build.Repository.LocalPath)/client-route-manager

# trigger when branch 'master' changes
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - client-route-manager/*

# do not trigger on pull requests to avoid that tag 'latest' is pushed for pull requests
pr: none

# trigger weekly rebuild every sunday 00:00 UTC
schedules:
- cron: "0 0 * * 0"
  displayName: Weekly Sunday Rebuild
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Login
  inputs:
    command: login
    containerregistry: Docker Hub
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    Dockerfile: $(basedir)/Dockerfile
    repository: $(repository)
    tags: $(image_tag)
- script: |
    sudo apt-get install python3-venv
    $(basedir)/tests/run-tests.sh
  displayName: Test
- task: Docker@2
  displayName: Push
  inputs:
    command: push
    repository: $(repository)
    tags: $(image_tag)
- script: |
      docker run \
      -v $PWD:/workspace \
      -e DOCKERHUB_USERNAME='$(registry_user)' \
      -e DOCKERHUB_PASSWORD='$(registry_password)' \
      -e DOCKERHUB_REPOSITORY='$(repository)' \
      -e README_FILEPATH='/workspace/README.md' \
      peterevans/dockerhub-description:2.0.0
  displayName: Update Image Description
- task: Docker@2
  displayName: Logout
  inputs:
    command: logout
    containerRegistry: Docker Hub
